# Generated by Django 5.1.1 on 2024-09-11 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recomendaciones", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personavulnerable",
            name="menores_a_cargo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="recomendaciones.personavulnerable",
            ),
        ),
    ]
