# Generated by Django 5.1.1 on 2024-09-07 23:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provincia', models.CharField(max_length=25)),
                ('calle', models.CharField(max_length=30)),
                ('altura', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonaVulnerable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recomendaciones.direccion')),
                ('menores_a_cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recomendaciones.personavulnerable')),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('latitud', models.DecimalField(decimal_places=4, max_digits=5)),
                ('longitud', models.DecimalField(decimal_places=4, max_digits=5)),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recomendaciones.direccion')),
            ],
        ),
    ]
