# Generated by Django 5.1.1 on 2024-09-07 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion',
            name='direccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recomendaciones.direccion'),
        ),
        migrations.AlterModelTable(
            name='direccion',
            table='direcciones',
        ),
        migrations.AlterModelTable(
            name='personavulnerable',
            table='personas_vulnerables',
        ),
        migrations.AlterModelTable(
            name='ubicacion',
            table='ubicaciones',
        ),
    ]
