# Generated by Django 5.1.1 on 2024-09-11 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recomendaciones", "0002_alter_personavulnerable_menores_a_cargo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personavulnerable",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
